package demo

import (
	"time"

	"github.com/CatSprite-dev/fireball/internal/api"
)

var demoPositions = []api.Position{
	// Russian shares
	{
		Figi:                 "BBG004730N88",
		Ticker:               "SBER",
		ClassCode:            "TQBR",
		InstrumentType:       "share",
		PositionUID:          "41eb2102-5333-4713-bf15-72b204c4bf7b",
		InstrumentUID:        "e6123145-9665-43e0-8413-cd61b8aa9b13",
		Quantity:             api.Quotation{Units: "100", Nano: 0},
		QuantityLots:         api.Quotation{Units: "1", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "rub", Units: "260", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "rub", Units: "308", Nano: 500_000_000},
		ExpectedYield:        api.Quotation{Units: "4850", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "rub", Units: "150", Nano: 0},
	},
	{
		Figi:                 "BBG004730RP0",
		Ticker:               "GAZP",
		ClassCode:            "TQBR",
		InstrumentType:       "share",
		PositionUID:          "4f9d0c81-cdf9-4735-8295-bacbfa3b8a51",
		InstrumentUID:        "962e2a95-02a9-4171-abd7-aa198dbe643a",
		Quantity:             api.Quotation{Units: "200", Nano: 0},
		QuantityLots:         api.Quotation{Units: "2", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "rub", Units: "180", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "rub", Units: "142", Nano: 300_000_000},
		ExpectedYield:        api.Quotation{Units: "-7540", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "rub", Units: "-80", Nano: 0},
	},
	{
		Figi:                 "BBG004731032",
		Ticker:               "LKOH",
		ClassCode:            "TQBR",
		InstrumentType:       "share",
		PositionUID:          "3213e01a-7bce-4946-b01e-5b0aaa3fc9b4",
		InstrumentUID:        "02cfdf61-6298-4c0f-a9ca-9cabc82afaf3",
		Quantity:             api.Quotation{Units: "15", Nano: 0},
		QuantityLots:         api.Quotation{Units: "1", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "rub", Units: "6200", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "rub", Units: "7450", Nano: 0},
		ExpectedYield:        api.Quotation{Units: "18750", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "rub", Units: "320", Nano: 0},
	},
	{
		Figi:                 "BBG004730JJ5",
		Ticker:               "MOEX",
		ClassCode:            "TQBR",
		InstrumentType:       "share",
		PositionUID:          "1b33fa68-cfc8-43e1-bd0e-2155d0199e7d",
		InstrumentUID:        "5e1c2634-afc4-4e50-ad6d-f78fc14a539a",
		Quantity:             api.Quotation{Units: "200", Nano: 0},
		QuantityLots:         api.Quotation{Units: "1", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "rub", Units: "148", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "rub", Units: "172", Nano: 0},
		ExpectedYield:        api.Quotation{Units: "4800", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "rub", Units: "180", Nano: 0},
	},
	{
		Figi:                 "BBG004731354",
		Ticker:               "ROSN",
		ClassCode:            "TQBR",
		InstrumentType:       "share",
		PositionUID:          "0a0acc65-84db-4ffc-b359-faa00de99d41",
		InstrumentUID:        "fd417230-19cf-4e7b-9623-f7c9ca18ec6b",
		Quantity:             api.Quotation{Units: "30", Nano: 0},
		QuantityLots:         api.Quotation{Units: "1", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "rub", Units: "520", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "rub", Units: "591", Nano: 0},
		ExpectedYield:        api.Quotation{Units: "2130", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "rub", Units: "45", Nano: 0},
	},
	{
		Figi:                 "BBG004731489",
		Ticker:               "GMKN",
		ClassCode:            "TQBR",
		InstrumentType:       "share",
		PositionUID:          "8dfc66ef-bd19-4cbc-91b6-22ab581d7dae",
		InstrumentUID:        "509edd0c-129c-4ee2-934d-7f6246126da1",
		Quantity:             api.Quotation{Units: "5", Nano: 0},
		QuantityLots:         api.Quotation{Units: "1", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "rub", Units: "15200", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "rub", Units: "13800", Nano: 0},
		ExpectedYield:        api.Quotation{Units: "-7000", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "rub", Units: "-210", Nano: 0},
	},
	// US shares (traded on SPB exchange)
	{
		Figi:                 "BBG000B9XRY4",
		Ticker:               "AAPL",
		ClassCode:            "SPBXM",
		InstrumentType:       "share",
		PositionUID:          "5c5e6656-c4d3-4391-a7ee-e81a76f1804e",
		InstrumentUID:        "a9eb4238-eba9-488c-b102-b6140fd08e38",
		Quantity:             api.Quotation{Units: "10", Nano: 0},
		QuantityLots:         api.Quotation{Units: "10", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "usd", Units: "155", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "usd", Units: "189", Nano: 500_000_000},
		ExpectedYield:        api.Quotation{Units: "345", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "usd", Units: "12", Nano: 0},
	},
	{
		Figi:                 "BBG000BBJQV0",
		Ticker:               "NVDA",
		ClassCode:            "SPBXM",
		InstrumentType:       "share",
		PositionUID:          "dfb42d57-3e57-4f6e-ab5a-f54882ced3b8",
		InstrumentUID:        "81575098-df8a-45c4-82dc-1b64374dcfdb",
		Quantity:             api.Quotation{Units: "5", Nano: 0},
		QuantityLots:         api.Quotation{Units: "5", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "usd", Units: "420", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "usd", Units: "875", Nano: 0},
		ExpectedYield:        api.Quotation{Units: "2275", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "usd", Units: "95", Nano: 0},
	},
	{
		Figi:                 "BBG000BPH459",
		Ticker:               "MSFT",
		ClassCode:            "SPBXM",
		InstrumentType:       "share",
		PositionUID:          "14ed5263-ac0f-49e8-b6bd-b9abc15699a0",
		InstrumentUID:        "99cfdf6a-8b64-44b1-b38e-c831f77d552d",
		Quantity:             api.Quotation{Units: "8", Nano: 0},
		QuantityLots:         api.Quotation{Units: "8", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "usd", Units: "310", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "usd", Units: "415", Nano: 0},
		ExpectedYield:        api.Quotation{Units: "840", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "usd", Units: "18", Nano: 0},
	},
	{
		Figi:                 "BBG000BVPV84",
		Ticker:               "AMZN",
		ClassCode:            "SPBXM",
		InstrumentType:       "share",
		PositionUID:          "c8b5a4af-9ef3-4208-a0e5-e99229f0ef45",
		InstrumentUID:        "6de4b6e2-dda9-4c49-9ba8-aa96dc15d33f",
		Quantity:             api.Quotation{Units: "6", Nano: 0},
		QuantityLots:         api.Quotation{Units: "6", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "usd", Units: "130", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "usd", Units: "185", Nano: 0},
		ExpectedYield:        api.Quotation{Units: "330", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "usd", Units: "8", Nano: 0},
	},
	// ETFs
	{
		Figi:                 "BBG00M0P2RX7",
		Ticker:               "ESGV",
		ClassCode:            "SPBXM",
		InstrumentType:       "etf",
		PositionUID:          "a08a53f1-0386-4eb9-b1b0-18781ba9b2af",
		InstrumentUID:        "dfcce902-3d23-4b9e-b131-668f2235293a",
		Quantity:             api.Quotation{Units: "500", Nano: 0},
		QuantityLots:         api.Quotation{Units: "5", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "usd", Units: "5", Nano: 800_000_000},
		CurrentPrice:         api.MoneyValue{Currency: "usd", Units: "6", Nano: 950_000_000},
		ExpectedYield:        api.Quotation{Units: "575", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "usd", Units: "15", Nano: 0},
	},
	{
		Figi:                 "TCS70A106DL2",
		Ticker:               "TMON@",
		ClassCode:            "SPBRU",
		InstrumentType:       "etf",
		PositionUID:          "96a4604c-79d9-4a30-8a46-95a80dfd9f02",
		InstrumentUID:        "498ec3ff-ef27-4729-9703-a5aac48d5789",
		Quantity:             api.Quotation{Units: "300", Nano: 0},
		QuantityLots:         api.Quotation{Units: "3", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "rub", Units: "14", Nano: 200_000_000},
		CurrentPrice:         api.MoneyValue{Currency: "rub", Units: "16", Nano: 800_000_000},
		ExpectedYield:        api.Quotation{Units: "780", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "rub", Units: "22", Nano: 0},
	},
	{
		Figi:                 "TCS00A1035S8",
		Ticker:               "STME",
		ClassCode:            "TQTF",
		InstrumentType:       "etf",
		PositionUID:          "eaea19a9-b487-4505-b962-6bc686df78ea",
		InstrumentUID:        "46887d8b-0bb4-4ce4-ae7a-a588495e8fb0",
		Quantity:             api.Quotation{Units: "40", Nano: 0},
		QuantityLots:         api.Quotation{Units: "4", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "rub", Units: "4800", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "rub", Units: "5250", Nano: 0},
		ExpectedYield:        api.Quotation{Units: "18000", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "rub", Units: "120", Nano: 0},
	},
	// Bonds
	{
		Figi:                 "BBG011FJ4HS6",
		Ticker:               "SU26238RMFS4",
		ClassCode:            "TQOB",
		InstrumentType:       "bond",
		PositionUID:          "a2413ca4-9e08-4c56-8e8b-7fe1e0a0648b",
		InstrumentUID:        "92b9e913-d7df-4164-bd83-1013c819bf44",
		Quantity:             api.Quotation{Units: "10", Nano: 0},
		QuantityLots:         api.Quotation{Units: "10", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "rub", Units: "960", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "rub", Units: "945", Nano: 0},
		ExpectedYield:        api.Quotation{Units: "-150", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "rub", Units: "2", Nano: 700_000_000},
		CurrentNkd:           api.MoneyValue{Currency: "rub", Units: "18", Nano: 500_000_000},
	},
	{
		Figi:                 "TCS00A106E90",
		Ticker:               "SU26243RMFS4",
		ClassCode:            "TQOB",
		InstrumentType:       "bond",
		PositionUID:          "b968924c-54b8-43b5-ae3e-c0adfd02f59b",
		InstrumentUID:        "0d46d347-0e03-44af-a617-a86ed4d07bba",
		Quantity:             api.Quotation{Units: "20", Nano: 0},
		QuantityLots:         api.Quotation{Units: "20", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "rub", Units: "980", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "rub", Units: "972", Nano: 0},
		ExpectedYield:        api.Quotation{Units: "-160", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "rub", Units: "5", Nano: 400_000_000},
		CurrentNkd:           api.MoneyValue{Currency: "rub", Units: "22", Nano: 100_000_000},
	},
	{
		Figi:                 "BBG00TGK62V9",
		Ticker:               "RU000A101M04",
		ClassCode:            "TQCB",
		InstrumentType:       "bond",
		PositionUID:          "dac76c51-2fd9-4113-b180-e9a79f4bf1a3",
		InstrumentUID:        "c310c817-183a-41d2-a2b1-b5eb8bdcfe66",
		Quantity:             api.Quotation{Units: "15", Nano: 0},
		QuantityLots:         api.Quotation{Units: "15", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "rub", Units: "1010", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "rub", Units: "1024", Nano: 0},
		ExpectedYield:        api.Quotation{Units: "210", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "rub", Units: "3", Nano: 200_000_000},
		CurrentNkd:           api.MoneyValue{Currency: "rub", Units: "15", Nano: 800_000_000},
	},
	// More Russian shares
	{
		Figi:                 "BBG004RVFFC0",
		Ticker:               "TATN",
		ClassCode:            "TQBR",
		InstrumentType:       "share",
		PositionUID:          "43ba384c-a484-4ee7-842d-59b80260fa3f",
		InstrumentUID:        "88468f6c-c67a-4fb4-a006-53eed803883c",
		Quantity:             api.Quotation{Units: "40", Nano: 0},
		QuantityLots:         api.Quotation{Units: "4", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "rub", Units: "680", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "rub", Units: "742", Nano: 0},
		ExpectedYield:        api.Quotation{Units: "2480", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "rub", Units: "68", Nano: 0},
	},
	{
		Figi:                 "BBG004RVFCY3",
		Ticker:               "MGNT",
		ClassCode:            "TQBR",
		InstrumentType:       "share",
		PositionUID:          "6980e298-3ef5-4a1d-9148-6aba5668aa69",
		InstrumentUID:        "ca845f68-6c43-44bc-b584-330d2a1e5eb7",
		Quantity:             api.Quotation{Units: "8", Nano: 0},
		QuantityLots:         api.Quotation{Units: "1", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "rub", Units: "5400", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "rub", Units: "6180", Nano: 0},
		ExpectedYield:        api.Quotation{Units: "6240", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "rub", Units: "145", Nano: 0},
	},
	{
		Figi:                 "BBG004S68B31",
		Ticker:               "ALRS",
		ClassCode:            "TQBR",
		InstrumentType:       "share",
		PositionUID:          "962f3a99-3b2d-4af6-995e-26be412b7b22",
		InstrumentUID:        "30817fea-20e6-4fee-ab1f-d20fc1a1bb72",
		Quantity:             api.Quotation{Units: "60", Nano: 0},
		QuantityLots:         api.Quotation{Units: "6", Nano: 0},
		AveragePositionPrice: api.MoneyValue{Currency: "rub", Units: "72", Nano: 0},
		CurrentPrice:         api.MoneyValue{Currency: "rub", Units: "68", Nano: 500_000_000},
		ExpectedYield:        api.Quotation{Units: "-210", Nano: 0},
		DailyYield:           api.MoneyValue{Currency: "rub", Units: "-8", Nano: 0},
	},
}

// demoOperations generates 3 years of fake buy/sell/dividend/input operations
// for the demo portfolio. Dates are hardcoded relative to a fixed base time
// so the chart looks realistic regardless of when demo mode is viewed.
func demoOperations() []api.UserOperations {
	base := time.Date(2023, 1, 1, 10, 0, 0, 0, time.UTC)

	items := []api.Item{
		// ── Deposits ────────────────────────────────────────────────────────────
		{
			ID:      "demo-op-001",
			Date:    base,
			Type:    "OPERATION_TYPE_INPUT",
			State:   "OPERATION_STATE_EXECUTED",
			Payment: api.MoneyValue{Currency: "rub", Units: "500000", Nano: 0},
		},
		{
			ID:      "demo-op-006",
			Date:    base.AddDate(0, 3, 0),
			Type:    "OPERATION_TYPE_INPUT",
			State:   "OPERATION_STATE_EXECUTED",
			Payment: api.MoneyValue{Currency: "rub", Units: "300000", Nano: 0},
		},
		{
			ID:      "demo-op-011",
			Date:    base.AddDate(0, 6, 0),
			Type:    "OPERATION_TYPE_INPUT",
			State:   "OPERATION_STATE_EXECUTED",
			Payment: api.MoneyValue{Currency: "rub", Units: "200000", Nano: 0},
		},
		{
			ID:      "demo-op-017",
			Date:    base.AddDate(1, 0, 0),
			Type:    "OPERATION_TYPE_INPUT",
			State:   "OPERATION_STATE_EXECUTED",
			Payment: api.MoneyValue{Currency: "rub", Units: "250000", Nano: 0},
		},
		{
			ID:      "demo-op-025",
			Date:    base.AddDate(1, 6, 0),
			Type:    "OPERATION_TYPE_INPUT",
			State:   "OPERATION_STATE_EXECUTED",
			Payment: api.MoneyValue{Currency: "rub", Units: "150000", Nano: 0},
		},
		{
			ID:      "demo-op-032",
			Date:    base.AddDate(2, 0, 0),
			Type:    "OPERATION_TYPE_INPUT",
			State:   "OPERATION_STATE_EXECUTED",
			Payment: api.MoneyValue{Currency: "rub", Units: "100000", Nano: 0},
		},

		// ── SBER ─────────────────────────────────────────────────────────────
		{
			ID:             "demo-op-002",
			Date:           base.AddDate(0, 0, 5),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG004730N88",
			Ticker:         "SBER",
			ClassCode:      "TQBR",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "41eb2102-5333-4713-bf15-72b204c4bf7b",
			Payment:        api.MoneyValue{Currency: "rub", Units: "-13000", Nano: 0},
			Price:          api.MoneyValue{Currency: "rub", Units: "130", Nano: 0},
			QuantityDone:   "100",
		},
		{
			ID:             "demo-op-003",
			Date:           base.AddDate(0, 2, 0),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG004730N88",
			Ticker:         "SBER",
			ClassCode:      "TQBR",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "41eb2102-5333-4713-bf15-72b204c4bf7b",
			Payment:        api.MoneyValue{Currency: "rub", Units: "-6500", Nano: 0},
			Price:          api.MoneyValue{Currency: "rub", Units: "260", Nano: 0},
			QuantityDone:   "25",
		},
		{
			ID:             "demo-op-010",
			Date:           base.AddDate(0, 6, 0),
			Type:           "OPERATION_TYPE_DIVIDEND",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG004730N88",
			Ticker:         "SBER",
			ClassCode:      "TQBR",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "41eb2102-5333-4713-bf15-72b204c4bf7b",
			Payment:        api.MoneyValue{Currency: "rub", Units: "2500", Nano: 0},
		},
		{
			ID:             "demo-op-030",
			Date:           base.AddDate(1, 9, 15),
			Type:           "OPERATION_TYPE_DIVIDEND",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG004730N88",
			Ticker:         "SBER",
			ClassCode:      "TQBR",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "41eb2102-5333-4713-bf15-72b204c4bf7b",
			Payment:        api.MoneyValue{Currency: "rub", Units: "3300", Nano: 0},
		},

		// ── GAZP ─────────────────────────────────────────────────────────────
		{
			ID:             "demo-op-004",
			Date:           base.AddDate(0, 1, 0),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG004730RP0",
			Ticker:         "GAZP",
			ClassCode:      "TQBR",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "4f9d0c81-cdf9-4735-8295-bacbfa3b8a51",
			Payment:        api.MoneyValue{Currency: "rub", Units: "-36000", Nano: 0},
			Price:          api.MoneyValue{Currency: "rub", Units: "180", Nano: 0},
			QuantityDone:   "200",
		},

		// ── LKOH ─────────────────────────────────────────────────────────────
		{
			ID:             "demo-op-005",
			Date:           base.AddDate(0, 1, 15),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG004731032",
			Ticker:         "LKOH",
			ClassCode:      "TQBR",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "3213e01a-7bce-4946-b01e-5b0aaa3fc9b4",
			Payment:        api.MoneyValue{Currency: "rub", Units: "-93000", Nano: 0},
			Price:          api.MoneyValue{Currency: "rub", Units: "6200", Nano: 0},
			QuantityDone:   "15",
		},
		{
			ID:             "demo-op-016",
			Date:           base.AddDate(0, 9, 0),
			Type:           "OPERATION_TYPE_DIVIDEND",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG004731032",
			Ticker:         "LKOH",
			ClassCode:      "TQBR",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "3213e01a-7bce-4946-b01e-5b0aaa3fc9b4",
			Payment:        api.MoneyValue{Currency: "rub", Units: "8250", Nano: 0},
		},
		{
			ID:             "demo-op-035",
			Date:           base.AddDate(2, 6, 0),
			Type:           "OPERATION_TYPE_DIVIDEND",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG004731032",
			Ticker:         "LKOH",
			ClassCode:      "TQBR",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "3213e01a-7bce-4946-b01e-5b0aaa3fc9b4",
			Payment:        api.MoneyValue{Currency: "rub", Units: "9750", Nano: 0},
		},

		// ── MOEX ─────────────────────────────────────────────────────────────
		{
			ID:             "demo-op-007",
			Date:           base.AddDate(0, 3, 5),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG004730JJ5",
			Ticker:         "MOEX",
			ClassCode:      "TQBR",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "1b33fa68-cfc8-43e1-bd0e-2155d0199e7d",
			Payment:        api.MoneyValue{Currency: "rub", Units: "-29600", Nano: 0},
			Price:          api.MoneyValue{Currency: "rub", Units: "148", Nano: 0},
			QuantityDone:   "200",
		},

		// ── AAPL ─────────────────────────────────────────────────────────────
		{
			ID:             "demo-op-008",
			Date:           base.AddDate(0, 3, 10),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG000B9XRY4",
			Ticker:         "AAPL",
			ClassCode:      "SPBXM",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "5c5e6656-c4d3-4391-a7ee-e81a76f1804e",
			Payment:        api.MoneyValue{Currency: "usd", Units: "-1550", Nano: 0},
			Price:          api.MoneyValue{Currency: "usd", Units: "155", Nano: 0},
			QuantityDone:   "10",
		},

		// ── NVDA ─────────────────────────────────────────────────────────────
		{
			ID:             "demo-op-009",
			Date:           base.AddDate(0, 4, 0),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG000BBJQV0",
			Ticker:         "NVDA",
			ClassCode:      "SPBXM",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "dfb42d57-3e57-4f6e-ab5a-f54882ced3b8",
			Payment:        api.MoneyValue{Currency: "usd", Units: "-2100", Nano: 0},
			Price:          api.MoneyValue{Currency: "usd", Units: "420", Nano: 0},
			QuantityDone:   "5",
		},

		// ── ESGV ETF ──────────────────────────────────────────────────────────
		{
			ID:             "demo-op-012",
			Date:           base.AddDate(0, 6, 5),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG00M0P2RX7",
			Ticker:         "ESGV",
			ClassCode:      "SPBXM",
			InstrumentKind: "INSTRUMENT_TYPE_ETF",
			PositionUID:    "a08a53f1-0386-4eb9-b1b0-18781ba9b2af",
			Payment:        api.MoneyValue{Currency: "usd", Units: "-2900", Nano: 0},
			Price:          api.MoneyValue{Currency: "usd", Units: "5", Nano: 800_000_000},
			QuantityDone:   "500",
		},

		// ── SU26238RMFS4 (OFZ) ───────────────────────────────────────────────
		{
			ID:             "demo-op-013",
			Date:           base.AddDate(0, 7, 0),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG011FJ4HS6",
			Ticker:         "SU26238RMFS4",
			ClassCode:      "TQOB",
			InstrumentKind: "INSTRUMENT_TYPE_BOND",
			PositionUID:    "a2413ca4-9e08-4c56-8e8b-7fe1e0a0648b",
			Payment:        api.MoneyValue{Currency: "rub", Units: "-9600", Nano: 0},
			Price:          api.MoneyValue{Currency: "rub", Units: "960", Nano: 0},
			QuantityDone:   "10",
		},
		{
			ID:             "demo-op-021",
			Date:           base.AddDate(1, 3, 0),
			Type:           "OPERATION_TYPE_COUPON",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG011FJ4HS6",
			Ticker:         "SU26238RMFS4",
			ClassCode:      "TQOB",
			InstrumentKind: "INSTRUMENT_TYPE_BOND",
			PositionUID:    "a2413ca4-9e08-4c56-8e8b-7fe1e0a0648b",
			Payment:        api.MoneyValue{Currency: "rub", Units: "385", Nano: 0},
		},
		{
			ID:             "demo-op-033",
			Date:           base.AddDate(2, 3, 0),
			Type:           "OPERATION_TYPE_COUPON",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG011FJ4HS6",
			Ticker:         "SU26238RMFS4",
			ClassCode:      "TQOB",
			InstrumentKind: "INSTRUMENT_TYPE_BOND",
			PositionUID:    "a2413ca4-9e08-4c56-8e8b-7fe1e0a0648b",
			Payment:        api.MoneyValue{Currency: "rub", Units: "385", Nano: 0},
		},

		// ── MSFT ─────────────────────────────────────────────────────────────
		{
			ID:             "demo-op-014",
			Date:           base.AddDate(0, 7, 10),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG000BPH459",
			Ticker:         "MSFT",
			ClassCode:      "SPBXM",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "14ed5263-ac0f-49e8-b6bd-b9abc15699a0",
			Payment:        api.MoneyValue{Currency: "usd", Units: "-2480", Nano: 0},
			Price:          api.MoneyValue{Currency: "usd", Units: "310", Nano: 0},
			QuantityDone:   "8",
		},

		// ── ROSN ─────────────────────────────────────────────────────────────
		{
			ID:             "demo-op-015",
			Date:           base.AddDate(0, 8, 0),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG004731354",
			Ticker:         "ROSN",
			ClassCode:      "TQBR",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "0a0acc65-84db-4ffc-b359-faa00de99d41",
			Payment:        api.MoneyValue{Currency: "rub", Units: "-15600", Nano: 0},
			Price:          api.MoneyValue{Currency: "rub", Units: "520", Nano: 0},
			QuantityDone:   "30",
		},

		// ── GMKN ─────────────────────────────────────────────────────────────
		{
			ID:             "demo-op-018",
			Date:           base.AddDate(1, 0, 10),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG004731489",
			Ticker:         "GMKN",
			ClassCode:      "TQBR",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "8dfc66ef-bd19-4cbc-91b6-22ab581d7dae",
			Payment:        api.MoneyValue{Currency: "rub", Units: "-76000", Nano: 0},
			Price:          api.MoneyValue{Currency: "rub", Units: "15200", Nano: 0},
			QuantityDone:   "5",
		},

		// ── TMON@ ETF ─────────────────────────────────────────────────────────
		{
			ID:             "demo-op-019",
			Date:           base.AddDate(1, 1, 0),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "TCS70A106DL2",
			Ticker:         "TMON@",
			ClassCode:      "SPBRU",
			InstrumentKind: "INSTRUMENT_TYPE_ETF",
			PositionUID:    "96a4604c-79d9-4a30-8a46-95a80dfd9f02",
			Payment:        api.MoneyValue{Currency: "rub", Units: "-4260", Nano: 0},
			Price:          api.MoneyValue{Currency: "rub", Units: "14", Nano: 200_000_000},
			QuantityDone:   "300",
		},

		// ── AMZN ─────────────────────────────────────────────────────────────
		{
			ID:             "demo-op-020",
			Date:           base.AddDate(1, 2, 0),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG000BVPV84",
			Ticker:         "AMZN",
			ClassCode:      "SPBXM",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "c8b5a4af-9ef3-4208-a0e5-e99229f0ef45",
			Payment:        api.MoneyValue{Currency: "usd", Units: "-780", Nano: 0},
			Price:          api.MoneyValue{Currency: "usd", Units: "130", Nano: 0},
			QuantityDone:   "6",
		},

		// ── TATN ─────────────────────────────────────────────────────────────
		{
			ID:             "demo-op-022",
			Date:           base.AddDate(1, 3, 5),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG004RVFFC0",
			Ticker:         "TATN",
			ClassCode:      "TQBR",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "43ba384c-a484-4ee7-842d-59b80260fa3f",
			Payment:        api.MoneyValue{Currency: "rub", Units: "-27200", Nano: 0},
			Price:          api.MoneyValue{Currency: "rub", Units: "680", Nano: 0},
			QuantityDone:   "40",
		},
		{
			ID:             "demo-op-031",
			Date:           base.AddDate(2, 0, 0),
			Type:           "OPERATION_TYPE_DIVIDEND",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG004RVFFC0",
			Ticker:         "TATN",
			ClassCode:      "TQBR",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "43ba384c-a484-4ee7-842d-59b80260fa3f",
			Payment:        api.MoneyValue{Currency: "rub", Units: "4800", Nano: 0},
		},

		// ── SU26243RMFS4 (OFZ) ───────────────────────────────────────────────
		{
			ID:             "demo-op-024",
			Date:           base.AddDate(1, 5, 0),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "TCS00A106E90",
			Ticker:         "SU26243RMFS4",
			ClassCode:      "TQOB",
			InstrumentKind: "INSTRUMENT_TYPE_BOND",
			PositionUID:    "b968924c-54b8-43b5-ae3e-c0adfd02f59b",
			Payment:        api.MoneyValue{Currency: "rub", Units: "-19600", Nano: 0},
			Price:          api.MoneyValue{Currency: "rub", Units: "980", Nano: 0},
			QuantityDone:   "20",
		},

		// ── STME ETF ──────────────────────────────────────────────────────────
		{
			ID:             "demo-op-026",
			Date:           base.AddDate(1, 6, 5),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "TCS00A1035S8",
			Ticker:         "STME",
			ClassCode:      "TQTF",
			InstrumentKind: "INSTRUMENT_TYPE_ETF",
			PositionUID:    "eaea19a9-b487-4505-b962-6bc686df78ea",
			Payment:        api.MoneyValue{Currency: "rub", Units: "-192000", Nano: 0},
			Price:          api.MoneyValue{Currency: "rub", Units: "4800", Nano: 0},
			QuantityDone:   "40",
		},

		// ── RU000A101M04 (corporate bond) ────────────────────────────────────
		{
			ID:             "demo-op-027",
			Date:           base.AddDate(1, 7, 0),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG00TGK62V9",
			Ticker:         "RU000A101M04",
			ClassCode:      "TQCB",
			InstrumentKind: "INSTRUMENT_TYPE_BOND",
			PositionUID:    "dac76c51-2fd9-4113-b180-e9a79f4bf1a3",
			Payment:        api.MoneyValue{Currency: "rub", Units: "-15150", Nano: 0},
			Price:          api.MoneyValue{Currency: "rub", Units: "1010", Nano: 0},
			QuantityDone:   "15",
		},
		{
			ID:             "demo-op-034",
			Date:           base.AddDate(2, 4, 0),
			Type:           "OPERATION_TYPE_COUPON",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG00TGK62V9",
			Ticker:         "RU000A101M04",
			ClassCode:      "TQCB",
			InstrumentKind: "INSTRUMENT_TYPE_BOND",
			PositionUID:    "dac76c51-2fd9-4113-b180-e9a79f4bf1a3",
			Payment:        api.MoneyValue{Currency: "rub", Units: "720", Nano: 0},
		},

		// ── MGNT ─────────────────────────────────────────────────────────────
		{
			ID:             "demo-op-028",
			Date:           base.AddDate(1, 8, 0),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG004RVFCY3",
			Ticker:         "MGNT",
			ClassCode:      "TQBR",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "6980e298-3ef5-4a1d-9148-6aba5668aa69",
			Payment:        api.MoneyValue{Currency: "rub", Units: "-43200", Nano: 0},
			Price:          api.MoneyValue{Currency: "rub", Units: "5400", Nano: 0},
			QuantityDone:   "8",
		},

		// ── ALRS ─────────────────────────────────────────────────────────────
		{
			ID:             "demo-op-029",
			Date:           base.AddDate(1, 9, 0),
			Type:           "OPERATION_TYPE_BUY",
			State:          "OPERATION_STATE_EXECUTED",
			Figi:           "BBG004S68B31",
			Ticker:         "ALRS",
			ClassCode:      "TQBR",
			InstrumentKind: "INSTRUMENT_TYPE_SHARE",
			PositionUID:    "962f3a99-3b2d-4af6-995e-26be412b7b22",
			Payment:        api.MoneyValue{Currency: "rub", Units: "-4320", Nano: 0},
			Price:          api.MoneyValue{Currency: "rub", Units: "72", Nano: 0},
			QuantityDone:   "60",
		},
	}

	return []api.UserOperations{
		{
			HasNext: false,
			Items:   items,
		},
	}
}

// demoportfolio builds the UserPortfolio totals from the positions above.
func demoPortfolio() api.UserPortfolio {
	return api.UserPortfolio{
		AccountID:             "demo-account",
		Positions:             demoPositions,
		TotalAmountShares:     api.MoneyValue{Currency: "rub", Units: "1337551", Nano: 0},
		TotalAmountBonds:      api.MoneyValue{Currency: "rub", Units: "44250", Nano: 0},
		TotalAmountEtf:        api.MoneyValue{Currency: "rub", Units: "527790", Nano: 0},
		TotalAmountCurrencies: api.MoneyValue{Currency: "rub", Units: "0", Nano: 0},
		TotalAmountFutures:    api.MoneyValue{Currency: "rub", Units: "0", Nano: 0},
		TotalAmountOptions:    api.MoneyValue{Currency: "rub", Units: "0", Nano: 0},
		TotalAmountSp:         api.MoneyValue{Currency: "rub", Units: "0", Nano: 0},
		TotalAmountPortfolio:  api.MoneyValue{Currency: "rub", Units: "1909591", Nano: 0},
		ExpectedYield:         api.Quotation{Units: "436038", Nano: 0},
		DailyYield:            api.MoneyValue{Currency: "rub", Units: "2890", Nano: 0},
		DailyYieldRelative:    api.Quotation{Units: "0", Nano: 151_000_000},
	}
}
